<?php
/**
 * Created by PhpStorm.
 * User: Home
 * Date: 04/06/2019
 * Time: 23:39
 */

namespace App\Tenant;


use App\Company;
use Illuminate\Database\Eloquent\Model;

trait TenantModels
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new TenantScope());

        static::creating(function (Model $obj) {
            $company = \Tenant::getTenant();
            if($company)
                $obj->company_id = $company->id;
        });
    }

    public function company(){
        return $this->belongsTo(Company::class);
    }
}
